### PR TITLE
Update Scala to 3.0.0-RC2

### PR DESCRIPTION
**Pull request by vlovgr**

### CODE REVIEW

**Comment by vlovgr** [comment]
@fthomas Looks like ciris-refined fails on Scala 3.0.0-RC2 with:

> [error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/C:/Users/vlovgr/Projects/ciris/"), "refined"):
> [error]    org.scala-lang.modules:scala-xml _2.13, _3.0.0-RC2

any idea what's going on?

**Comment by fthomas** [comment]
@vlovgr Could you check if it works with [refined 0.9.22+11-d5f2db6b-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/eu/timepit/refined_3.0.0-RC2/0.9.22+11-d5f2db6b-SNAPSHOT/) which includes https://github.com/fthomas/refined/pull/938? If yes, I'll publish a new version with this change.

**Comment by vlovgr** [comment]
@fthomas Now I'm getting:

```
[error] java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error] 
[error] 	* org.scala-lang.modules:scala-xml_2.12:2.0.0-RC1 (early-semver) is selected over 1.0.6
[error] 	    +- eu.timepit:refined_2.12:0.9.22+11-d5f2db6b-SNAPSHOT (depends on 2.0.0-RC1)
[error] 	    +- org.scala-lang:scala-compiler:2.12.13              (depends on 1.0.6)
```

and maybe it's fine to depend on 2.0.0-RC1 in Scala 2.12.13, or maybe refined will have to use 1.0.6 on 2.12.13 and 2.0.0-RC1 on Scala 3.0.0-RC2?

**Comment by fthomas** [comment]
> maybe refined will have to use 1.0.6 on Scala 2.x and 2.0.0-RC1 on Scala 3.0.0-RC2?

Done in https://github.com/fthomas/refined/pull/939 which is in [0.9.22+13-1c899eda-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/eu/timepit/refined_3.0.0-RC2/0.9.22+13-1c899eda-SNAPSHOT/). Maybe this works without errors. :crossed_fingers:

**Comment by vlovgr** [comment]
@fthomas Looks like the build is passing now. Thanks! 🎉:+1:

Would be great if you could push a stable release when you get a chance as well. :)

**Comment by fthomas** [comment]
Great, that the build is passing. I just pushed the v0.9.23 tag which should result in a new release soon.

**Pull request merged**
