### PR TITLE
Work in Progress: Concurrent Parallel

### PR DESCRIPTION
**Pull request by zarthross**
## Problem: 
When running `.parMapN` or `parTraverse` over `ConfigValue`s the errors accumulate (which is good), but the underlying `IO`s are ran sequentially.  For some cases this is unnoticeable, but for loading large amount of configuration from slow sources (with high concurrency limits) this is slow.  

With pre 1.0 version you could hack around this by switching between `Monad` and `Applicative` types (using `Parallel`)

I personally had a HTTP service I would load config from which required dozens of calls, each taking 1~4 seconds.  It could serve all of them in parallel in about the same time.  
Pre 1.0 with parallel hack, I could my application configuration in 4 seconds, after upgrading to 1.X it took over 30 seconds.

## Goals:
- Keep binary compatibility with the current interface (as much as possible)
- Add support for calling `load` and `resource` with a `Parallel` instance to perform concurrent configuration loading.

## Solution:
- Move all anonymous instances of `ConfigValue` to named instances, and added a `toPar` implementation.
- Add `toPar` that takes in a `Parallel` instance that is used when the `ConfigValue` being run is explicitly from an `Ap` operation.
- `to` is re-implemented using a `Parallel.identity` to simply implementation and reduce redundancy.

## Todo:
- [ ] Add calls to `toPar` like `load` and `resource` that `to` has.

## Comments:
I know I touched more areas of the code than likely was strictly necessary, but I did manage to not impact the tests at all during the refactors. I would LOVE some peer review on this and any notes of improvement to get this merged in so I and others can take advantage of the changes.

### CODE REVIEW

**Comment by vlovgr** [comment]
Thanks for raising this pull request @zarthross!

I think it's an oversight that `parMapN` doesn't also load the values in parallel (it should likely be the default).
I'm tempted to leave this for Cats Effect 3, as [the change](https://github.com/vlovgr/ciris/commit/108232894288cf38ade6ed57d1b673d1b1695de8) is small and doesn't require `Parallel` any more.

**Comment by zarthross** [comment]
I took a glance over at the branch you linked, and yeah, the change to add par looks like a very small change comparatively. 


 This may be the wrong thread to discus the ce3 branch, but i don't see an open PR or issue for it, sooo.... Are you changing `ConfigValue` back so that it has the effect type like was done in pre 1.X branch?  This is a huge change... and if so, I might stop my efforts of migrating to 1.2 until this is finalized since i don't want to thread back in the `F` after just ripping it out of all my code...

Whats the motivation for changing back?  What was the motivation for changing in the first place?

**Comment by vlovgr** [comment]
> I took a glance over at the branch you linked, and yeah, the change to add par looks like a very small change comparatively.

Note this change is the same regardless of whether we go with `ConfigValue[+F[_], A]` or `ConfigValue[A]`, hence my temptation to wait for Cats Effect 3 to implement this change.

>  This may be the wrong thread to discus the ce3 branch, but i don't see an open PR or issue for it, sooo.... Are you changing `ConfigValue` back so that it has the effect type like was done in pre 1.X branch?  This is a huge change... and if so, I might stop my efforts of migrating to 1.2 until this is finalized since i don't want to thread back in the `F` after just ripping it out of all my code...
>
> Whats the motivation for changing back?  What was the motivation for changing in the first place?

The `ce3` branch is just a working proposal. I'll open a pull request explaining the changes once I feel it's ready for review. In short: the proposal is to change to `ConfigValue[+F[_], A]` and use inference tricks (similar to fs2's `Stream`) to avoid having to explicitly specify the effect type like in the 0.x series. In a way it's a hybrid between 0.x and 1.x, but which let's us keep the syntax of 1.x (not having to explicitly specify the effect type for every value). 

The motivation behind the change is to support `eval` and `evalMap` with `Effect` removed in Cats Effect 3. If we want to stay with `ConfigValue[A]`, `eval` and `evalMap` will have to have a `UnsafeRun` contstraint, which I'd really like to avoid. If you're interested, you can read the discussions around it [here](https://gitter.im/vlovgr/ciris?at=5f8c9a5ec7ef520fffac7143).

**Comment by vlovgr** [comment]
Closing this in favour of #416.

**Pull request closed without merging**
