### PR TITLE
Add SingleUsePassword

### PR DESCRIPTION
**Pull request by adrian-salajan**
One might want to use a password just once to initialise something, after that the password should not stay in memory.

### CODE REVIEW

**Comment by adrian-salajan** [comment]
I'm not sure which implementation is the better/correct one
` SingleUsePassword[F[_]] private (private val password: PasswordProtection) ` - current PR
vs
` SingleUsePassword[F[_]] private (private val password: Resource[F,PasswordProtection]) ` - first commit in this PR

**Comment by vlovgr** [comment]
Hey, thanks for raising this.

You might want to have a look at [SafePassword](https://alexn.org/snippets/2020/08/27/safe-password.scala.html) as reference.

**Comment by adrian-salajan** [comment]
> Hey, thanks for raising this.
> 
> You might want to have a look at [SafePassword](https://alexn.org/snippets/2020/08/27/safe-password.scala.html) as reference.

Hi, I saw it, actually it was what triggered this attempt :)  

1. i guess it is better to use PasswordProtection as a core type
2. it might be safer to not use String anywhere, for construction or returning the password, to avoid any JVM string interning stuff
3. i suspect my initial design of the class `SingleUsePassword[F[_]] private (private val password: Resource[F,PasswordProtection])` might be safer since it is a description of a computation so it avoids any storing of the password until the computation is run

**Comment by vlovgr** [comment]
@adrian-salajan Sorry for leaving this for so long. But I'd like to get this merged (in some form) for the next release candidate. I've also opened #457 to showcase an alternative implementation to the one in this pull request.

> i guess it is better to use PasswordProtection as a core type

I don't see it providing any benefit. It uses `Arrays.fill(chars, ' ')` which is what I've opted for in #457 as well.

> it might be safer to not use String anywhere, for construction or returning the password, to avoid any JVM string interning stuff

I agree it makes sense to use `Array[Char]` everywhere for security, even though it's mutable. I've opted for this in #457.

**Comment by vlovgr** [comment]
Closing in favour of #457.

**Pull request closed without merging**
